note: 'target-adaptation'

model: 'deeplab'
use_rl: True
step_0: False
gmm: True

ece_train: True
multigpu: False
fixbn: True
fix_seed: True

freeze_encoder: True
freeze_value_net: True

train: True

encoder_train: True
decoder_train: True
encoder: True
decoder: True

# Optimizers
optim: 'sgd'
learning_rate: 0.00005 
num_steps: 500000
epochs: 20
weight_decay: 0.0005 
momentum: 0.9
power: 0.9
round: 1

# cos ann warm
T_0: 5
T_mult: 1


# target Plabel
cb_prop: 0.15
num_center: 10
lamb: 0.5
local_prop: 0.1
threshold: 0.8


# source Image Selection
src_count: 1191
src_pix_prop: 0.9
src_pix_select: True
pool_prop: 0.2

# Selction and Fix 
src_fix: False
tgt_fix: False
src_select: True
tgt_select: True

# Re start training
resume: False
start: 0
round_start: 5

# Logging
print_freq: 1
save_freq: 2000
screen: True
val: True
val_freq: 2000

# Dataset 
source: 'gta5'
target: 'cityscapes'
worker: 4
batch_size: 4
# Transforms
input_src: 720
input_tgt: 720
crop_src: 600
crop_tgt: 600
mirror: True
scale_min: 0.5
scale_max: 1.5
rec: False
img_prop: 0.1

init_weight: None

snapshot: None
result: None
log: None
plabel: None

rl_restore_from: None
restore_from: None
num_classes: 19

gta5: {
        data_dir: '/Cal-SFDA/GTA5/',
        data_list: '/Cal-SFDA/dataset/list/gta5_train.txt',
        data_list_val: '/Cal-SFDA/dataset/list/gta5_val.txt',
        input_size: [1280, 720]
        }
synthia: {
        data_dir: '/Cal-SFDA/synthia/RAND_CITYSCAPES/',
        data_list: '/Cal-SFDA/dataset/list/synthia_train.txt',
        input_size: [1280, 760]
        }
cityscapes: {
        data_dir: '/Cal-SFDA/cityscapes/',
        data_list: '/Cal-SFDA/dataset/list/cityscapes_train.txt',
        input_size: [1024, 512]
        }