note: 'train-rl-source-only-ece'


use_rl: True
step_0: False

model: 'deeplab'
ece_train: True
multigpu: False
fixbn: True
fix_seed: True


train: True

alpha: 1


encoder_train: True
decoder_train: True
encoder: True
decoder: True


learning_rate: 0.00005
num_steps: 5000
epochs: 30
weight_decay: 0.0005
momentum: 0.9
power: 0.9
round: 6
clip: 0.01  

# Logging
print_freq: 1
save_freq: 2000
tensorboard: True
screen: True
val: True
val_freq: 2000

# Dataset 
source: 'gta5'
target: 'cityscapes'
worker: 4
batch_size: 4

# Transforms
input_src: 720
input_tgt: 720
crop_src: 600
crop_tgt: 600
mirror: True
scale_min: 0.5
scale_max: 1.5
rec: False

# Model hypers restore from the best model
init_weight: None
restore_from: None
rl_restore_from: None
snapshot: None
result: None
log: None

gta5: {
        data_dir: '/Cal-SFDA/GTA5/',
        data_list: '/Cal-SFDA/dataset/list/gta5_train.txt',
        data_list_val: '/Cal-SFDA/dataset/list/gta5_val.txt',
        input_size: [1280, 720]
        }
synthia: {
        data_dir: '/Cal-SFDA/synthia/RAND_CITYSCAPES/',
        data_list: '/Cal-SFDA/dataset/list/synthia_train.txt',
        input_size: [1280, 760]
        }
cityscapes: {
        data_dir: '/Cal-SFDA/cityscapes/',
        data_list: '/Cal-SFDA/dataset/list/cityscapes_train.txt',
        input_size: [1024, 512]
        }